### ISSUE TITLE
Good work wrapping sections in container divs

### ISSUE THREAD

**Issue by griffinlacek** [DebDebMN/prj-rev-bwfs-dasmoto#2]
You've got all your code sections inside container divs, which is great for readability and makes layout/styling easier! This is a good practice so keep it up!

Just as a note, I always like to indent my comments to meet the indentation of the section they refer to, as it's a bit more readable to me!

https://github.com/DebDebMN/prj-rev-bwfs-dasmoto/blob/master/deb-b-mn-Dasmoto/index.html#L13-L37

**Comment by DebDebMN** [comment]
Excellent suggestion!   And I've updated my comments.
