### ISSUE TITLE
Targeting html in CSS

### ISSUE THREAD

**Issue by griffinlacek** [DebDebMN/prj-rev-bwfs-dasmoto#3]
Nothing wrong with using html to set font-family for the page, but body is often used instead as it directly influences children elements. Here's a good discussion on this: https://css-tricks.com/html-vs-body-in-css/

https://github.com/DebDebMN/prj-rev-bwfs-dasmoto/blob/master/deb-b-mn-Dasmoto/Resources/CSS/style.css#L1-L3

**Comment by DebDebMN** [comment]
Thank you for the suggestion!  And the interesting discussion.  I've updated my CSS file.
