### ISSUE TITLE
Commenting on height/width of h1

### ISSUE THREAD

**Issue by griffinlacek** [DebDebMN/prj-rev-bwfs-dasmoto#4]
Not sure if the background wasn't appearing without these styles, but by default width and height are set to auto, so unless it wasn't working before adding these styles then it should be defaulting to these values regardless!

https://github.com/DebDebMN/prj-rev-bwfs-dasmoto/blob/master/deb-b-mn-Dasmoto/Resources/CSS/style.css#L12-L13

**Comment by DebDebMN** [comment]
I noticed that when I shrunk the webpage in my browser, the "Dasmoto's Arts & Crafts" became two lines however the background image did not - leaving "& Crafts" out on white space.  So I added the auto and that took care of the issue.
