### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by griffinlacek** [DebDebMN/prj-rev-bwfs-dasmoto#5]
**Grade:** Exceeds Expectations

**Summary:** This project is good! It meets the spec and the code is clean/free of any errors. No major areas of improvement to note, so keep up the good work (indentation, comments, are good habits!).

As a further challenge, think about and try to change the page to have the item divs horizontally aligned instead of vertical aligned. There’s a few different ways to do this, but one way involves set widths and inline-block styling! This is a good resource for learning more: http://learnlayout.com/inline- block.html.

I’d also suggest checking out HTML codes, which will help explain my comment on the & usage in your HTML!

Good work!

**Comment by DebDebMN** [comment]
Thank you for your review, excellent comments and pointers to great learning aids.  Very much appreciated!
